/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_reservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class frmroom extends javax.swing.JFrame {

    /**
     * Creates new form frmroom
     */
    public frmroom() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void showTable()
    {
        try
        {
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conobj = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelreservationdb","root","");
            String sql="select * from roomtbl";
            PreparedStatement pst=conobj.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblroom.setModel(DbUtils.resultSetToTableModel(rs));
            conobj.close();
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txthid = new javax.swing.JTextField();
        txtnoofbeds = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        lblroomtype = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblroom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtupdateroomid = new javax.swing.JTextField();
        cmbroomtype = new javax.swing.JComboBox<>();
        btnback = new javax.swing.JButton();
        cmdbedtype = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204), 2));

        btnadd.setBackground(new java.awt.Color(204, 255, 255));
        btnadd.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(204, 255, 255));
        btndelete.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(204, 255, 255));
        btnupdate.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        lblroomtype.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lblroomtype.setForeground(new java.awt.Color(255, 255, 255));
        lblroomtype.setText("Room Type");

        tblroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Hotel ID", "Room type", "Number of beds", "Bed type"
            }
        ));
        jScrollPane1.setViewportView(tblroom);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No of beds");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hotel ID");

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Room ID(for update details)");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bed type");

        txtupdateroomid.setToolTipText("Please enter room id for update record");

        cmbroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "for one person", "for two person", "for four person" }));

        btnback.setBackground(new java.awt.Color(204, 255, 255));
        btnback.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        cmdbedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single bed", "Double bed" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblroomtype, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txthid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbroomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnoofbeds, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdbedtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnupdate)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnback)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtupdateroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txthid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblroomtype)
                            .addComponent(cmbroomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnoofbeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmdbedtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtupdateroomid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(btnback)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(btndelete)
                            .addComponent(btnupdate))
                        .addGap(36, 36, 36))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Rooms");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        if(txthid.getText().equals("") || txtnoofbeds.getText().equals("") || cmbroomtype.getSelectedItem().toString().equals("")
                || cmdbedtype.getSelectedItem().toString().equals(""))
        {
           JOptionPane.showMessageDialog(this,"Please Enter All Data");
        }
        else
        {
            String n=txtnoofbeds.getText();
            String hotelid=txthid.getText();
            try
            {
              Integer.parseInt(n);
            }
            catch(NumberFormatException e)
            {
               JOptionPane.showMessageDialog(this,"Please Enter No of beds");
            }
            try
            {
              Integer.parseInt(hotelid);
            }
            catch(NumberFormatException e)
            {
               JOptionPane.showMessageDialog(this,"Please Enter valid hotel id");
            }
            int hid=Integer.parseInt(txthid.getText());
            int noofbed=Integer.parseInt(txtnoofbeds.getText());
            String roomtype=cmbroomtype.getSelectedItem().toString();
            String bedtype=cmdbedtype.getSelectedItem().toString();
            
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conobj = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelreservationdb","root","");
            String sql="insert into roomtbl(hotelid,roomtype,no_of_bed,bedtype)values(?,?,?,?)";
            PreparedStatement pst = conobj.prepareStatement(sql);
            pst.setInt(1, hid);
            pst.setString(2,roomtype);
            pst.setInt(3, noofbed);
            pst.setString(4,bedtype);
            
            
            pst.executeUpdate();
            
                JOptionPane.showMessageDialog(null,"Data Insert Successfully");
                showTable();
                txthid.setText("");
                txtnoofbeds.setText("");
               
            
            conobj.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        
        }
        
        }    
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        
        if(txthid.getText().equals("") )
        {
           JOptionPane.showMessageDialog(this,"Please Enter Data");
        }
        else
        {
            String n=txtnoofbeds.getText();
            String hotelid=txthid.getText();
            try
            {
              Integer.parseInt(n);
            }
            catch(NumberFormatException e)
            {
               JOptionPane.showMessageDialog(this,"Please Enter No of beds");
            }
            try
            {
              Integer.parseInt(hotelid);
            }
            catch(NumberFormatException e)
            {
               JOptionPane.showMessageDialog(this,"Please Enter valid hotel id");
            }
            
            
            int hid=Integer.parseInt(txthid.getText());
            int noofbed=Integer.parseInt(txtnoofbeds.getText());
            String roomtype=cmbroomtype.getSelectedItem().toString();
            String bedtype=cmdbedtype.getSelectedItem().toString();
            
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conobj = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelreservationdb","root","");
            String sql="delete from roomtbl where hotelid=? AND roomtype=? AND no_of_bed=? AND bedtype=?";
            PreparedStatement pst = conobj.prepareStatement(sql);
            
            pst.setInt(1,hid);
            pst.setString(2,roomtype);
            pst.setInt(3,noofbed);
            pst.setString(4,bedtype);
            
            pst.executeUpdate();
            
                JOptionPane.showMessageDialog(null,"Data Remove Successfully");
                showTable();
                txthid.setText("");
                txtnoofbeds.setText("");
                
            conobj.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        
        }
                
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if(txthid.getText().equals("") || cmbroomtype.getSelectedItem().toString().equals("") || 
                cmdbedtype.getSelectedItem().toString().equals("")|| txtupdateroomid.getText().equals(""))
        {
           JOptionPane.showMessageDialog(this,"Please Enter All Data");
        }
        else
        {
            String n=txtnoofbeds.getText();
            String hotelid=txthid.getText();
            String roomid=txtupdateroomid.getText();
            try
            {
              Integer.parseInt(n);
            }
            catch(NumberFormatException e)
            {
               JOptionPane.showMessageDialog(this,"Please Enter No of beds");
            }
            try
            {
              Integer.parseInt(hotelid);
            }
            catch(NumberFormatException e)
            {
               JOptionPane.showMessageDialog(this,"Please Enter valid hotel id");
            }
            try
            {
              Integer.parseInt(roomid);
            }
            catch(NumberFormatException e)
            {
               JOptionPane.showMessageDialog(this,"Please Enter valid room id");
            }
            int hid=Integer.parseInt(txthid.getText());
            int noofbed=Integer.parseInt(txtnoofbeds.getText());
            String roomtype=cmbroomtype.getSelectedItem().toString();
            String bedtype=cmdbedtype.getSelectedItem().toString();
            int rid=Integer.parseInt(txtupdateroomid.getText());
            
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conobj = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelreservationdb","root","");
            String sql="update roomtbl SET roomtype =? ,no_of_bed =?,bedtype=? where hotelid =? AND roomid=?";
            PreparedStatement pst = conobj.prepareStatement(sql);
            
            pst.setString(1,roomtype);
            pst.setInt(2,noofbed);
            pst.setString(3, bedtype);
            pst.setInt(4,hid);
            pst.setInt(5,rid);
            pst.executeUpdate();
            
                JOptionPane.showMessageDialog(null,"Data Update Successfully");
                showTable();
                txthid.setText("");
                txtnoofbeds.setText("");
               
            
            conobj.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        
        }
                
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        emphandle emp=new emphandle();
             emp.setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbroomtype;
    private javax.swing.JComboBox<String> cmdbedtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblroomtype;
    private javax.swing.JTable tblroom;
    private javax.swing.JTextField txthid;
    private javax.swing.JTextField txtnoofbeds;
    private javax.swing.JTextField txtupdateroomid;
    // End of variables declaration//GEN-END:variables
}
